### ISSUE TITLE
Problem with color of selection_bg

### ISSUE THREAD

**Issue by KhoaLee** [sho-87/kanagawa-paper.vscode#1]
With the current selection_bg, the highlight of text on selection going to be hard to see as in image below:
![image](https://github.com/sho-87/kanagawa-paper.vscode/assets/33981342/499a2b52-bd54-4d9b-baca-64ae783227c6)

In contrast, when I remove the cursor to focus on different macOS windows or apps, the selection_bg seem to be easier to see.
![image](https://github.com/sho-87/kanagawa-paper.vscode/assets/33981342/aa37e68e-1810-48b7-8070-de91234e3d8f)

Hope you can update a better color for selection highlight text bg color. I love the idea of this theme but this is the only constraint I think it has

**Comment by thesimonho** [comment]
good catch. a few options for you, let me know which you prefer...

1. same color as currently, but just darker (#3e5263):
![image](https://github.com/sho-87/kanagawa-paper.vscode/assets/5199715/b2341b51-447b-4331-aa46-93d125429890)

2. on the neovim side I use one of the sumiInk colors. this is sumiInk6 (#54546D):
![image](https://github.com/sho-87/kanagawa-paper.vscode/assets/5199715/3d42fff4-e17d-4c4d-a735-4020a41de1ad)

3. this is sumiInk5 (#363646), which favors text readability over seeing the actual highlight:
![image](https://github.com/sho-87/kanagawa-paper.vscode/assets/5199715/f61df891-622f-4f63-bb42-ee0be46c74c3)

**Comment by KhoaLee** [comment]
I think option 3 is good as a personal preference, it matches the background color best

**Comment by thesimonho** [comment]
yep agreed. i just pushed out an update. thanks for the feedback!
