### ISSUE TITLE
Would you please export a version for JetBrains IDEs?

### ISSUE THREAD

**Issue by miranquil** [sho-87/kanagawa-paper.vscode#2]
I love this theme very much. But due to compatibility reason I cannot use VSCode as main editor in my office dev environment. I've searched solutions but nothing worked. An export would be helpful a lot. And thanks for your hard working!

**Comment by thesimonho** [comment]
I dont use any of the jetbrains products so can't really help much there. have you tried something like this? found it after a quick google search: https://github.com/JetBrains/colorSchemeTool

**Comment by miranquil** [comment]
Thank you for you kindly reply! I've already tried this convert tool. It worked all in all but only editor scheme affected, the terminal and IDE main color theme were ignored. And I've tried to check the JSON in this repository to customize one but the working was not very satisfying.
I'm considering to try more customizing to make a better ported version when I have enough spare time.

**Comment by thesimonho** [comment]
you can also look at my nvim repo, which I maintain more actively and has ports for different applications. maybe there'll be something there that will help with jetbrains. good luck with your port if you ever get around to it!
