### ISSUE TITLE
Cursor not visible in integrated terminal

### ISSUE THREAD

**Issue by alsoicode** [sho-87/kanagawa-paper.vscode#3]
Love the theme, but the cursor is no longer visible in the integrated terminal.

![Screenshot 2024-12-02 at 9 08 50 AM](https://github.com/user-attachments/assets/7a52346a-7d81-435a-a7a2-1e935509ec01)

What settings can I alter / check to correct this?

**Comment by thesimonho** [comment]
ah good catch. will push out a fix

**Comment by alsoicode** [comment]
Thank you very much!
